export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_SCROLLBAR = 'SET_SCROLLBAR'

export const SET_SCROLLOFFSET = 'SET_SCROLLOFFSET'

export const SET_BLURNAV = 'SET_BLURNAV'

export const SET_TRANSITION = 'SET_TRANSITION'

export const TOGGLE_MOBILENAV = 'TOGGLE_MOBILENAV'

export const SET_WORMHOLE_CACHE = 'SET_WORMHOLE_CACHE'

export const SET_FIREWORK_CACHE = 'SET_FIREWORK_CACHE'

