export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_SCROLLBAR = 'SET_SCROLLBAR'

export const SET_SCROLLOFFSET = 'SET_SCROLLOFFSET'

export const SET_BLURNAV = 'SET_BLURNAV'

export const TOGGLE_MOBILENAV = 'TOGGLE_MOBILENAV'
